services:
  - type: web
    name: movie-python-downloader
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000
    disk:
      name: downloads
      mountPath: /opt/render/project/src/downloads
      sizeGB: 10